#!/bin/bash

# Example usage:
#   git branch-info | sort | cut -f 2-
# If the remote you want to compare against isn't "origin", set UPSTREAM=upstream
#   UPSTREAM=upstream git branch-info | sort | cut -f 2-
# If the remote HEAD branch isn't "main", set `HEAD=master` (change as appropriate)

set -euo pipefail

upstream=${UPSTREAM:=origin}
head=${HEAD:=main}

for branch in $(git for-each-ref --format='%(refname)' "refs/remotes/${upstream}/"); do
    if [[ $branch == "refs/remotes/origin/HEAD" ]]; then continue; fi
    echo -e \
        "$(git show --format="%ci\t%cr" "${branch}" | head -n 1)" "\t" \
        "${branch//refs\/remotes\/${upstream}\//}" "\t" \
        "$(git log --format="%ae" "${upstream}/${head}..${branch}" | sed -e "s/@.*//" | sort | uniq -c | sort -nr | awk '{print $2 " (" $1 ")"}' | xargs)"
done
