#!/bin/bash

# Example usage:
#   git branch-info | sort | cut -f 2-
# If the remote you want to compare against isn't "origin", set UPSTREAM=upstream
#   UPSTREAM=upstream git branch-info | sort | cut -f 2-

set -euo pipefail

upstream=${UPSTREAM:=origin}

for branch in $(git for-each-ref --format='%(refname)' refs/remotes/${upstream}/); do
    if [[ $branch == "refs/remotes/origin/HEAD" ]] ; then continue; fi
    echo -e \
        "$(git show --format="%ci\t%cr" "${branch}" | head -n 1)" "\t" \
        "$(echo "${branch}" | sed -e "s!refs/remotes/${upstream}/!!")" "\t" \
        "$(git log --format="%ae" ${upstream}/master.."${branch}" | sed -e "s/@.*//" | sort | uniq -c | sort -nr | awk '{print $2 " (" $1 ")"}' | xargs)"
done
