#!/bin/bash

# Example usage:
#   git branch-info | sort | cut -f 2-

for branch in $(git for-each-ref --format='%(refname)' refs/remotes/origin/); do
    if [[ $branch == "refs/remotes/origin/HEAD" ]] ; then continue; fi
    echo -e \
        "$(git show --format="%ci\t%cr" "${branch}" | head -n 1)" "\t" \
        "$(echo "${branch}" | sed -e "s!refs/remotes/origin/!!")" "\t" \
        "$(git log --format="%ae" origin/master.."${branch}" | sed -e "s/@.*//" | sort | uniq -c | sort -nr | awk '{print $2 " (" $1 ")"}' | xargs)"
done
